In [19]:
import pandas as pd

In [67]:
revenu = pd.read_csv('data/revenu_departement_insee_2011.csv')
revenu.head(5)

  CODGEO                   LIBGEO  MENIMP11  QUAR2UC11
0     01                      Ain     62.50      20533
1     02                    Aisne     54.30      16854
2     03                   Allier     54.21      17526
3     04  Alpes-de-Haute-Provence     56.05      18057
4     05             Hautes-Alpes     57.90      18375

In [68]:
 revenu = revenu.rename(columns={'CODGEO': 'Codep', 'LIBGEO': 'LibDept', 'MENIMP11': '%imposé', 'QUAR2UC11': 'revenuMed'})

In [123]:
revenu = revenu.set_index('Codep')
revenu.head(5)

                       LibDept  %imposé  revenuMed
Codep
01                         Ain    62.50      20533
02                       Aisne    54.30      16854
03                      Allier    54.21      17526
04     Alpes-de-Haute-Provence    56.05      18057
05                Hautes-Alpes    57.90      18375

In [25]:
revenu.dtypes

CodeDept      object
LibDept       object
%imposé      float64
revenuMed      int64
dtype: object

In [130]:
effectifs = pd.read_csv('data/damir2013_2.csv' ,sep=';')
effectifs = effectifs.rename(columns={'effectifs': 'nb_gen'})
effectifs = effectifs.set_index('codep')
effectifs = effectifs.drop(['mode_exercice', 'zone_inscription', 'specialite', 'sexe'], axis=1)
# recalculons les colonnes pour avoir des numériques
effectifs['acte_affilies']=effectifs.nb_actes/effectifs.pop_affiliee
# remarque : densité de medecins pour 100000 habitants
effectifs['densite_medecins']=effectifs.nb_gen/effectifs.pop_affiliee*100000
effectifs.head(5)

,year,l_dpt,nb_actes,annee,nb_gen,pop_affiliee,acte_affilies,densite_medecins
codep,,,,,,,,
01,2013,01-Ain,1636398,2013,682,478280,3.421423,142.594296
02,2013,02-Aisne,2041417,2013,636,459020,4.447338,138.556054
03,2013,03-Allier,1097580,2013,500,283425,3.872559,176.413513
04,2013,04-Alpes-haute-Provence,538365,2013,292,132280,4.069890,220.743877
05,2013,05-Hautes-Alpes,409929,2013,321,110535,3.708590,290.405754

In [94]:
# nombre d'actes total France 2013
effectifs.nb_actes.sum()

234095541

In [132]:
effectifs.shape

(101, 8)

In [131]:
effectifs.dtypes

year                  int64
l_dpt                object
nb_actes              int64
annee                 int64
nb_gen                int64
pop_affiliee          int64
acte_affilies       float64
densite_medecins    float64
dtype: object

In [44]:
nb_2013 = pd.read_csv('data/nb_2013.csv')
nb_2013.head(110)

,l_dpt,dpt,0 à 4 ans,5 à 9 ans,10 à 14 ans,15 à 19 ans,20 à 24 ans,25 à 29 ans,30 à 34 ans,35 à 39 ans,...,45 à 49 ans.1,50 à 54 ans.1,55 à 59 ans.1,60 à 64 ans.1,65 à 69 ans.1,70 à 74 ans.1,75 à 79 ans.1,80 à 84 ans.1,85 à 89 ans.1,90 ans et plus.1
0,01-Ain,01,15867.0,17144.0,17067.0,14504.0,12810.0,14795.0,15964.0,16049.0,...,18207.0,16323.0,15230.0,14902.0,11719.0,8184.0,7236.0,6257.0,4211.0,2652.0
1,02-Aisne,02,15192.0,15710.0,15838.0,13914.0,12548.0,13798.0,14237.0,13930.0,...,16633.0,16685.0,16465.0,16132.0,11483.0,8334.0,8600.0,7868.0,5053.0,2540.0
2,03-Allier,03,7407.0,7918.0,8303.0,7644.0,7111.0,7053.0,7656.0,7944.0,...,10300.0,10584.0,10832.0,11338.0,9467.0,7106.0,7242.0,6495.0,4482.0,2534.0
3,04-Alpes-haute-Provence,04,3382.0,3961.0,4146.0,3728.0,3237.0,3400.0,3448.0,3432.0,...,5214.0,5143.0,4773.0,5126.0,4549.0,3489.0,2975.0,2494.0,1722.0,1097.0
4,05-Hautes-Alpes,05,3064.0,3177.0,3406.0,2966.0,2602.0,3125.0,3199.0,3121.0,...,4362.0,4364.0,4188.0,4158.0,3562.0,2582.0,2324.0,1970.0,1351.0,822.0
5,06-Alpes-maritimes,06,26834.0,26684.0,27542.0,28033.0,31827.0,30984.0,32540.0,32014.0,...,39587.0,36335.0,34360.0,34726.0,32428.0,25479.0,23806.0,21620.0,15956.0,11148.0
6,07-Ardèche,07,7550.0,8436.0,8616.0,7291.0,6228.0,6907.0,7215.0,7729.0,...,10053.0,9441.0,9515.0,9886.0,8222.0,5925.0,5430.0,4775.0,3406.0,2102.0
7,08-Ardennes,08,7433.0,7967.0,8159.0,7371.0,6516.0,7225.0,7286.0,7427.0,...,9252.0,9012.0,8823.0,8503.0,6032.0,4593.0,4908.0,4329.0,2687.0,1356.0
8,09-Ariège,09,3252.0,3498.0,3575.0,3235.0,2709.0,2949.0,3212.0,3479.0,...,4551.0,4730.0,4557.0,4654.0,3799.0,2707.0,2776.0,2461.0,1628.0,1054.0
9,10-Aube,10,8369.0,8351.0,7831.0,7388.0,7104.0,7563.0,7882.0,7708.0,...,9049.0,9046.0,9066.0,9101.0,6985.0,5272.0,5171.0,4506.0,3151.0,1909.0
10,11-Aude,11,8048.0,8399.0,8716.0,7630.0,6468.0,7161.0,7586.0,7659.0,...,10718.0,10139.0,10302.0,11258.0,9904.0,6596.0,5992.0,5199.0,3427.0,1978.0
11,12-Aveyron,12,5625.0,5998.0,6082.0,5265.0,4942.0,5555.0,5882.0,5867.0,...,7666.0,7504.0,7273.0,7687.0,6170.0,4785.0,4628.0,4050.0,2614.0,1606.0
12,13-Bouches-du-Rhône,13,57007.0,57079.0,56814.0,57409.0,63405.0,58845.0,60073.0,60319.0,...,70069.0,65153.0,61725.0,59807.0,50217.0,37761.0,34625.0,30357.0,21167.0,13284.0
13,14-Calvados,14,18118.0,18964.0,18959.0,20115.0,21455.0,18525.0,18818.0,18489.0,...,21028.0,20994.0,21406.0,21532.0,16063.0,11643.0,11517.0,9969.0,6552.0,3899.0
14,15-Cantal,15,2494.0,2798.0,2791.0,2489.0,2346.0,2733.0,2822.0,2957.0,...,4107.0,4151.0,4262.0,4267.0,3323.0,2488.0,2465.0,2135.0,1316.0,860.0
15,16-Charente,16,7798.0,8350.0,8604.0,7454.0,6953.0,7583.0,7905.0,8109.0,...,10875.0,10826.0,11196.0,11186.0,8974.0,6407.0,6188.0,5386.0,3653.0,2324.0
16,17-Charente-maritime,17,13630.0,14370.0,15178.0,14533.0,15160.0,13943.0,14157.0,14080.0,...,18290.0,18150.0,19214.0,21419.0,18317.0,12652.0,11687.0,10012.0,7060.0,4355.0
17,18-Cher,18,7123.0,7420.0,7609.0,6987.0,6639.0,6746.0,6949.0,7043.0,...,9655.0,9802.0,9553.0,10350.0,8349.0,6164.0,6316.0,5519.0,3734.0,2164.0
18,19-Corrèze,19,4880.0,5269.0,5358.0,4698.0,4529.0,4811.0,5123.0,5463.0,...,7100.0,7291.0,7370.0,7639.0,6040.0,4650.0,4539.0,4063.0,2847.0,1692.0
19,2A-Corse Sud,2A,3036.0,3019.0,3214.0,2906.0,2971.0,3483.0,3724.0,3729.0,...,4819.0,4451.0,4263.0,4028.0,3324.0,2773.0,2428.0,2068.0,1416.0,872.0
20,2B-Haute Corse,2B,3294.0,3252.0,3370.0,3474.0,3827.0,3624.0,3796.0,3867.0,...,5030.0,4815.0,4506.0,4422.0,3772.0,2984.0,2652.0,2274.0,1522.0,998.0
21,21-Côte-d'Or,21,12856.0,13282.0,13543.0,14628.0,16979.0,14891.0,14115.0,13539.0,...,16181.0,16337.0,15880.0,15824.0,12058.0,8944.0,8556.0,7345.0,5252.0,3280.0
22,22-Côtes-d'Armor,22,13234.0,14560.0,14978.0,13259.0,11550.0,12088.0,12801.0,13216.0,...,16154.0,16511.0,16819.0,18920.0,15324.0,10879.0,10602.0,8877.0,6023.0,3415.0
23,23-Creuse,23,2055.0,2246.0,2437.0,2144.0,2001.0,2052.0,2203.0,2258.0,...,3411.0,3631.0,3701.0,3978.0,3044.0,2186.0,2236.0,1980.0,1347.0,842.0
24,24-Dordogne,24,7780.0,8501.0,9049.0,8214.0,7304.0,7815.0,8283.0,8286.0,...,12090.0,12161.0,12549.0,14026.0,11533.0,8311.0,7760.0,7026.0,4766.0,2757.0
25,25-Doubs,25,14304.0,14701.0,14155.0,14523.0,15672.0,14961.0,15486.0,14584.0,...,15416.0,15164.0,14854.0,14690.0,11689.0,8939.0,8551.0,7342.0,4848.0,2649.0
26,26-Drôme,26,13280.0,13956.0,14026.0,12711.0,11532.0,11985.0,12514.0,12385.0,...,15781.0,14870.0,14401.0,14384.0,12338.0,9150.0,8087.0,6945.0,4631.0,2751.0
27,27-Eure,27,17940.0,18502.0,18601.0,15338.0,13300.0,15481.0,16719.0,17092.0,...,18950.0,18384.0,18020.0,17622.0,12873.0,8997.0,8702.0,7094.0,4785.0,2731.0
28,28-Eure-et-Loir,28,11826.0,12365.0,11603.0,10213.0,9298.0,10858.0,11682.0,11933.0,...,11893.0,11332.0,11298.0,11182.0,8466.0,6001.0,5839.0,4984.0,3459.0,2179.0
29,29-Finistère,29,20068.0,21637.0,21965.0,21427.0,20693.0,20128.0,21304.0,21538.0,...,25521.0,24938.0,24511.0,25540.0,19978.0,14807.0,15105.0,13059.0,8697.0,4520.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,72-Sarthe,72,15855.0,16653.0,16466.0,15414.0,14119.0,14045.0,14679.0,15475.0,...,17260.0,16652.0,16704.0,16584.0,12316.0,9405.0,9575.0,8052.0,5282.0,3177.0
78,73-Savoie,73,10225.0,10681.0,11093.0,10352.0,11511.0,11291.0,11828.0,11753.0,...,12796.0,12120.0,11257.0,11372.0,9251.0,6987.0,6485.0,5552.0,3840.0,2185.0
79,74-Haute-Savoie,74,20126.0,21173.0,21041.0,19776.0,16984.0,20648.0,23038.0,22565.0,...,24125.0,21806.0,19626.0,19675.0,16246.0,11622.0,10141.0,8388.0,5628.0,3237.0
80,75-Paris,75,62697.0,61467.0,59444.0,70145.0,105882.0,106603.0,112853.0,113063.0,...,90973.0,83006.0,78344.0,74188.0,58808.0,41488.0,35879.0,31899.0,23924.0,17215.0
81,76-Seine-maritime,76,12126.0,12071.0,12109.0,11692.0,12359.0,12701.0,11990.0,11780.0,...,12726.0,12915.0,12893.0,12373.0,9127.0,6673.0,6672.0,6004.0,3878.0,2160.0
82,76-Seine-maritime,76,24700.0,24481.0,24256.0,25206.0,28946.0,26746.0,25943.0,24554.0,...,27503.0,27711.0,26996.0,26057.0,19671.0,14182.0,14526.0,12555.0,8309.0,4768.0
83,77-Seine-et-Marne,77,43922.0,43437.0,41975.0,37484.0,37103.0,41034.0,43117.0,42462.0,...,44621.0,40693.0,38029.0,34622.0,25040.0,17222.0,16004.0,13312.0,8762.0,5475.0
84,78-Yvelines,78,46446.0,47420.0,46744.0,41464.0,34308.0,42625.0,46722.0,48992.0,...,50280.0,46273.0,41917.0,38805.0,30285.0,22301.0,20506.0,17145.0,11109.0,6856.0
85,79-Deux-Sèvres,79,9248.0,9866.0,9487.0,8162.0,7177.0,8318.0,8968.0,9231.0,...,11189.0,10941.0,10784.0,10834.0,8237.0,5841.0,5532.0,4564.0,3106.0,1822.0
86,80-Somme,80,15861.0,16058.0,16221.0,17051.0,20322.0,16609.0,16320.0,16145.0,...,17524.0,17054.0,16997.0,17110.0,12715.0,8784.0,8774.0,7697.0,4991.0,2688.0
87,81-Tarn,81,9067.0,9459.0,9590.0,9003.0,8309.0,8038.0,8773.0,9048.0,...,11621.0,11311.0,11190.0,11590.0,9365.0,6830.0,6658.0,6127.0,4189.0,2407.0
88,82-Tarn-et-Garonne,82,6651.0,6829.0,6504.0,5527.0,4671.0,5276.0,5904.0,6205.0,...,7356.0,7035.0,6715.0,6664.0,5341.0,3853.0,3602.0,3021.0,2147.0,1239.0
89,83-Var,83,23268.0,23719.0,25226.0,23838.0,23088.0,23183.0,23352.0,23506.0,...,33691.0,31677.0,30938.0,33422.0,31373.0,23919.0,21346.0,18186.0,12577.0,8091.0
90,84-Vaucluse,84,14531.0,14661.0,14449.0,14215.0,13851.0,14323.0,14246.0,13884.0,...,17269.0,16203.0,15245.0,15447.0,13314.0,9964.0,8680.0,7515.0,5101.0,3184.0
91,85-Vendée,85,17244.0,17886.0,17163.0,15145.0,13814.0,15134.0,16992.0,16774.0,...,18354.0,18162.0,17762.0,20209.0,15790.0,11251.0,10799.0,8505.0,5853.0,3257.0
92,86-Vienne,86,10937.0,11081.0,10930.0,11893.0,14736.0,11400.0,11346.0,11149.0,...,12694.0,12595.0,13075.0,12461.0,9544.0,6914.0,6677.0,5817.0,4013.0,2409.0
93,87-Haute-Vienne,87,8418.0,8364.0,8298.0,8729.0,9673.0,8803.0,8987.0,9205.0,...,10691.0,10195.0,10573.0,11398.0,9191.0,6460.0,6455.0,5961.0,4239.0,2423.0
94,88-Vosges,88,8609.0,9214.0,9819.0,9198.0,8450.0,8995.0,9326.0,9393.0,...,11119.0,11199.0,10909.0,11651.0,8888.0,6685.0,7088.0,6419.0,4210.0,2293.0
95,89-Yonne,89,8643.0,8894.0,9242.0,8077.0,7148.0,8033.0,8306.0,8314.0,...,10255.0,10330.0,10369.0,10979.0,8345.0,6262.0,6299.0,5585.0,4046.0,2526.0
96,90-Territoire de Belfort,90,4122.0,4358.0,4160.0,4626.0,5879.0,4444.0,4353.0,4365.0,...,4633.0,4644.0,4456.0,4364.0,3153.0,2489.0,2505.0,2193.0,1460.0,838.0
97,91-Essonne,91,41741.0,41468.0,39369.0,36694.0,39038.0,38994.0,40857.0,42833.0,...,42221.0,38290.0,33658.0,31461.0,24589.0,18512.0,17169.0,13764.0,8932.0,5373.0
98,92-Hauts-de-Seine,92,53940.0,49827.0,45203.0,40055.0,39000.0,52318.0,62598.0,61907.0,...,56347.0,49572.0,43497.0,40285.0,32005.0,23842.0,23034.0,21833.0,15520.0,10145.0
99,93-Seine-saint-Denis,93,60373.0,57843.0,52204.0,46323.0,47473.0,52848.0,58776.0,60014.0,...,51855.0,48420.0,44356.0,37165.0,25517.0,19335.0,19160.0,16387.0,10167.0,6009.0
100,94-Val-de-Marne,94,44679.0,42756.0,39955.0,37574.0,41050.0,44407.0,48943.0,48869.0,...,47132.0,43522.0,40122.0,36643.0,27756.0,20958.0,20511.0,18714.0,13385.0,7825.0
101,95-Val-d'Oise,95,43768.0,42840.0,39355.0,35614.0,36076.0,40174.0,42688.0,42772.0,...,40947.0,39040.0,35376.0,30918.0,21515.0,15730.0,14730.0,12583.0,8332.0,4827.0
102,971-Guadeloupe,971,12929.0,15596.0,16510.0,15646.0,10926.0,8745.0,9116.0,11597.0,...,18753.0,16848.0,14457.0,12646.0,9582.0,7174.0,5979.0,4205.0,2888.0,1974.0
103,972-Martinique,972,10646.0,12096.0,13351.0,12603.0,10230.0,8333.0,8024.0,9405.0,...,17495.0,16127.0,13822.0,11831.0,9258.0,7700.0,6853.0,4871.0,3162.0,2349.0
104,973-Guyane,973,9243.0,10571.0,10159.0,8546.0,5380.0,4664.0,4809.0,5072.0,...,5817.0,4983.0,4049.0,3046.0,1879.0,1241.0,893.0,578.0,373.0,334.0
105,974-Réunion,974,33686.0,36096.0,36176.0,33553.0,28125.0,26254.0,25686.0,26995.0,...,33168.0,27543.0,23447.0,17885.0,13182.0,10770.0,8600.0,5687.0,3689.0,2199.0
106,976-Mayotte,976,9158.0,7414.0,6759.0,6102.0,3085.0,2446.0,3144.0,3708.0,...,2592.0,2245.0,1777.0,1223.0,782.0,660.0,435.0,321.0,138.0,121.0

### quelle difference entre les colonnes suffixées 1 ?

In [66]:
nb_2013[['80 à 84 ans','80 à 84 ans.1']].head(5)

   80 à 84 ans  80 à 84 ans.1
0       3925.0         6257.0
1       4080.0         7868.0
2       3594.0         6495.0
3       1557.0         2494.0
4       1185.0         1970.0

#### vu l'évolution de la difference selon l'age les suffixes .1 sont les données des femmes

### essayons de comprendre si ces nombres représentent des nombres de personnes ou d'actes

In [159]:
nb_2013.set_index(['dpt']).melt(id_vars="l_dpt", var_name="tranche_age").value.sum()

58095926.0

### c'est donc bien des personnes !

In [194]:
population = nb_2013
population.head(5)

,l_dpt,dpt,0 à 4 ans,5 à 9 ans,10 à 14 ans,15 à 19 ans,20 à 24 ans,25 à 29 ans,30 à 34 ans,35 à 39 ans,...,45 à 49 ans.1,50 à 54 ans.1,55 à 59 ans.1,60 à 64 ans.1,65 à 69 ans.1,70 à 74 ans.1,75 à 79 ans.1,80 à 84 ans.1,85 à 89 ans.1,90 ans et plus.1
0,01-Ain,01,15867.0,17144.0,17067.0,14504.0,12810.0,14795.0,15964.0,16049.0,...,18207.0,16323.0,15230.0,14902.0,11719.0,8184.0,7236.0,6257.0,4211.0,2652.0
1,02-Aisne,02,15192.0,15710.0,15838.0,13914.0,12548.0,13798.0,14237.0,13930.0,...,16633.0,16685.0,16465.0,16132.0,11483.0,8334.0,8600.0,7868.0,5053.0,2540.0
2,03-Allier,03,7407.0,7918.0,8303.0,7644.0,7111.0,7053.0,7656.0,7944.0,...,10300.0,10584.0,10832.0,11338.0,9467.0,7106.0,7242.0,6495.0,4482.0,2534.0
3,04-Alpes-haute-Provence,04,3382.0,3961.0,4146.0,3728.0,3237.0,3400.0,3448.0,3432.0,...,5214.0,5143.0,4773.0,5126.0,4549.0,3489.0,2975.0,2494.0,1722.0,1097.0
4,05-Hautes-Alpes,05,3064.0,3177.0,3406.0,2966.0,2602.0,3125.0,3199.0,3121.0,...,4362.0,4364.0,4188.0,4158.0,3562.0,2582.0,2324.0,1970.0,1351.0,822.0

### nous avons donc :
- des effectifs de généralistes et des nbr d'actes par département -> effectifs
- des chiffres hommes et femmes sur la population par département -> population
- des niveaux de revenus par département -> revenu

### Cherchons une corrélation entre la densité de médecins et le nombre d'actes par affilié

In [100]:
from scipy.stats import pearsonr

In [136]:
data1 = effectifs['acte_affilies']
data2 = effectifs['densite_medecins']

In [137]:
# calculate Pearson's correlation
corr, _ = pearsonr(data1, data2)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: 0.461

#### Corrélation faible...

### Cherchons une corrélation entre la densité de médecins et le revenu

In [182]:
# ayant mis le codep en index dans les 2 dataframes, on peut join implicite
# certaines données outre mer sont manquantes -> dropna
eff_rev = effectifs.join(revenu).dropna()
eff_rev.shape

(96, 11)

In [183]:
eff_rev.head(5)

,year,l_dpt,nb_actes,annee,nb_gen,pop_affiliee,acte_affilies,densite_medecins,LibDept,%imposé,revenuMed
codep,,,,,,,,,,,
01,2013,01-Ain,1636398,2013,682,478280,3.421423,142.594296,Ain,62.50,20533.0
02,2013,02-Aisne,2041417,2013,636,459020,4.447338,138.556054,Aisne,54.30,16854.0
03,2013,03-Allier,1097580,2013,500,283425,3.872559,176.413513,Allier,54.21,17526.0
04,2013,04-Alpes-haute-Provence,538365,2013,292,132280,4.069890,220.743877,Alpes-de-Haute-Provence,56.05,18057.0
05,2013,05-Hautes-Alpes,409929,2013,321,110535,3.708590,290.405754,Hautes-Alpes,57.90,18375.0

In [184]:
data1 = eff_rev['revenuMed']
data2 = eff_rev['densite_medecins']

In [185]:
# calculate Pearson's correlation
corr, _ = pearsonr(data1, data2)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: -0.153

#### Corrélation encore plus faible...

### Pour le fun regardons la corrélation entre le % d'imposition et le revenu

In [186]:
data1 = eff_rev['revenuMed']
data2 = eff_rev['%imposé']

In [187]:
# calculate Pearson's correlation
corr, _ = pearsonr(data1, data2)
print('Pearsons correlation: %.3f' % corr)

Pearsons correlation: 0.917

### ouf enfin une corrélation attendue ;-)

### Vérifions que la population d'affiliés est cohérente par département entre les Dataframes population et effectifs

In [198]:
pop_dep = population.set_index(['l_dpt']).melt(id_vars="dpt", var_name="tranche_age")
pop_dep = pop_dep.drop(['tranche_age'],axis=1).groupby('dpt').sum()
pop_dep.head(5)

        value
dpt
01   478280.0
02   459020.0
03   283425.0
04   132280.0
05   110535.0

In [201]:
ecart = pop_dep.join(effectifs).value - pop_dep.join(effectifs).pop_affiliee
ecart.sum()

0.0

#### Les dataframes sont cohérents !